### ISSUE TITLE
V4: _reactNativeCssInterop.createInteropElement is not a function

### ISSUE THREAD

**Issue by matallui** [nativewind/nativewind#823]
**Describe the bug**
After upgrading from NativeWind v4.0.23 to v4.0.36 (latest), my Expo SDK 50 app stopped working on Web.
Even if I remove all the markup and bring things down to a simple "Hello World" screen, nothing seems to work.

**To Reproduce**
Unfortunately I can't share the app I'm working on, but can provide any config/versions as needed.

Honestly, all I have to do is start the app now `expo start --web -c` and it will hit the error as seen in the screenshot below.

**Expected behavior**
Expected my app to work as it did before the update.

**Screenshots**
<img width="1144" alt="Screenshot 2024-02-23 at 10 30 52 AM" src="https://github.com/marklawlor/nativewind/assets/6828071/32b0db2d-bcfe-40c7-a467-b22eeeada93a">

**Additional context**
This is running in a Turbo Repo, but again, it was all working before the update.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
