### ISSUE TITLE
Nativewind not working with expo v53

### ISSUE THREAD

**Issue by henryornellas** [nativewind/nativewind#1483]
**Describe the bug**
Nativewind styles not being applied to react native app with expo v53

**Reproduction**
REPO:
https://github.com/henryornellas/nativewind-expo-issue

**Expected behavior**
Nativewind styles to be applied

**Comment by iamhenry** [comment]
im also having issue. following thread

**Comment by billyjacoby** [comment]
I'm having the same issue as well

**Comment by danstepanov** [comment]
Thanks for this repro @henryornellas, taking a look today and will chat with mark about it on tomorrow's stream (2:30pm PT), it will be recorded and available on YouTube.

**Comment by ArafatXLabs** [comment]
I am also stuck with my app that was built upon v52, and in v53 it is not applying the styles at all. The problem could be responsible for the metro.config.js file, which is unnecessary or needs to be set up differently in the updated version.

**Comment by iamhenry** [comment]
i think my issue was related to how it was using flexbox or grids because it would not display the calendar cells in full height

when i did tweak it, other things would break and cause scrolling glitchiness 

![Image](https://github.com/user-attachments/assets/04e6a2df-a46b-4924-8930-065f1cf573d0)

**Comment by thompsonnoah** [comment]
Also having some issues when attempting to style some `TextInput`s using NativeWind with Expo 53. Using the `style` prop works, but NativeWind does not.

**Comment by danstepanov** [comment]
Mark is now focusing on this issue thanks to this repro. Either he or I will update once we have a working solution.

**Comment by robertmunceanu** [comment]
did you try using **cssInterop**?

ex: cssInterop(ImageBackground, { className: 'style' });

https://www.nativewind.dev/docs/api/css-interop

**Comment by yungkittty** [comment]
same here, any workaround while it's fixed ?

**Comment by gilhrpenner** [comment]
Same issue here, following thread

**Comment by jasperaelvoet** [comment]
Using cssInterop does in fact fix it for me.

Example:
```js
import { LinearGradient } from "expo-linear-gradient";

cssInterop(LinearGradient, { className: "style" });
```

I would have expected all components to work out of the box, just like in version 2.

**Comment by danstepanov** [comment]
Hey y'all, we are wrapping up a fix for this today. Will discuss on today's stream at 5:30pm ET.

**Comment by billyjacoby** [comment]
> Hey y'all, we are wrapping up a fix for this today. Will discuss on today's stream at 5:30pm ET.

Where do you guys stream? I tried to find it last time you mentioned it and couldn't seem to find any links to a stream.

**Comment by D3OXY** [comment]
Any updates?

**Comment by gilhrpenner** [comment]
> Any updates?

He just said it? They are wrapping up a fix for today, will discuss on the livestream.

**Comment by abelgascia** [comment]
I think he will stream on his [YouTube channel](https://www.youtube.com/@dan_stepanov) or [X account](https://x.com/danstepanov)

**Comment by danstepanov** [comment]
Yea, I stream on [YouTube](https://youtube.com/@dan_stepanov), [Twitch](https://twitch.tv/notonlydans), and [Twitter](https://x.com/danstepanov)

**Comment by marklawlor** [comment]
@henryornellas This is an invalid reproduction, you need to rename `metro-config.js` to `metro.config.js`

**Comment by marklawlor** [comment]
People in this issue are reporting different things (TextInput, gradients, styled) - there is no one fix to these issues and we cannot resolve your particular issue without a reproduction issue.

If your issue is more specific than "If I add nativewind to npx create-expo-app then it doesn't work" can you please create a new issue. We'll keep this one open just for reports of Nativewind not working with the default Expo template. This is to help us isolate between issues with SDK 53 and Nativewind.

**Comment by billyjacoby** [comment]
> [henryornellas](https://github.com/henryornellas) This is an invalid reproduction, you need to rename `metro-config.js` to `metro.config.js`

**Comment by marklawlor** [comment]
> > [henryornellas](https://github.com/henryornellas) This is an invalid reproduction, you need to rename `metro-config.js` to `metro.config.js`
> 
> @marklawlor Was this the resolution here? If so I'll work on a different MRE because this is preventing me from upgrading to SDK 53 right now. 
> 
> 

Yes, if I renamed the file and cleared the cache the styles worked.

**Comment by billyjacoby** [comment]
> > > [henryornellas](https://github.com/henryornellas) This is an invalid reproduction, you need to rename `metro-config.js` to `metro.config.js`
> > 
> > 
> > [@marklawlor](https://github.com/marklawlor) Was this the resolution here? If so I'll work on a different MRE because this is preventing me from upgrading to SDK 53 right now.
> 
> Yes, if I renamed the file and cleared the cache the styles worked.

Okay I dug a little deeper this evening and it looks like my issue is specifically with css variables. I'll work on getting a reproduction tomorrow.

**Comment by garethlegrange** [comment]
I am having the same issue with Expo SDK 53

**Comment by anilyavas** [comment]
I mean metro.config.js does not even worked, still have styling issues somehow.

**Comment by Dakuan** [comment]
``` ERROR  Warning: Error: Your 'metro.config.js' has overridden the 'config.resolver.resolveRequest' config setting in a non-composable manner. Your styles will not work until this issue is resolved. Note that 'require('metro-config').mergeConfig' is a shallow merge and does not compose existing resolveRequest functions together.```

**Comment by BrookJeynes** [comment]
+1 styles not working at all when following the getting started docs.
pulling the example project also fails to have styles working with the latest expo

**Comment by gmacmaster** [comment]
+1 on styles not working with a fresh project following the getting started

**Comment by Dakuan** [comment]
is it working on a fresh expo53 project then?

**Comment by OzanOcak** [comment]
Yes it is working on a new project but if you try to set it up on an
existing project, it doesn’t

**Comment by Dakuan** [comment]
its just that I started a project yesterday, and it doesnt work. all ive done is follow the install steps on the docs.

**Comment by gilhrpenner** [comment]
@Dakuan I literally just created one and it worked first try, can you share your repo so we can help?

**Comment by umardev500** [comment]
> > its just that I started a project yesterday, and it doesnt work. all ive done is follow the install steps on the docs.
> 
> same here. getting errors. tried a fresh install like in docs.
> 
> whats the best way to get it set up on a fresh expo using `bun create expo my-app`. 

What's the error?
I just using bun/node it's worked


I think you guys just missing some setup step or typo

**Comment by LLcryptoJ** [comment]
> > > its just that I started a project yesterday, and it doesnt work. all ive done is follow the install steps on the docs.
> > 
> > 
> > same here. getting errors. tried a fresh install like in docs.
> > whats the best way to get it set up on a fresh expo using `bun create expo my-app`.
> 
> What's the error? I just using bun/node it's worked
> 
> I think you guys just missing some setup step or typo

works now for me. had to adjust themedview and themedtext components (which came with the fresh install) to not override nativewind.

**Comment by cpojer** [comment]
If you are having issues, clone this template and everything will work out of the box fully configured:

https://github.com/nkzw-tech/expo-app-template

**Comment by oyerohabib** [comment]
I have been facing the same issue of NativeWind not working in a project initiated without it and Expo SDK 53 for weeks but glad I finally found a way around it.

I think this, https://www.nativewind.dev/docs/guides/troubleshooting, is a great starting point for debugging. First clear the cache using the command "npx expo start --clear" then proceed with the other debugging steps.

When I ran this command, "npx tailwindcss --input <input.css> --output output.css," the output.css file was empty, even while I had my global.css file with the Tailwind import directives. Then I thought, "There must probably be something wrong with the installation." I also tried verifying the NativeWind installation using the guide here, https://www.nativewind.dev/docs/guides/troubleshooting#verifying-nativewind-installation, but it gave an error. 

Then, I deleted my node_modules folder and reinstalled the entire package using the command "npm i" and then followed the NativeWind manual setup guide again, following the guide here: https://www.nativewind.dev/docs/getting-started/installation. I previously had Tailwind CSS in the dependency instead of devDependencies.

Also, I updated my tailwind.config.js file correctly to contain the app and component folders.

`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
}`

Following the details carefully in the installation guide should help a lot, and be sure to verify the NativeWind installation, https://www.nativewind.dev/docs/guides/troubleshooting#verifying-nativewind-installation.

`import { verifyInstallation } from "nativewind";

export default function AuthScreen() {
  const nativewind = verifyInstallation();
  console.log("nativewind: ", nativewind);
  // remaining code`

It now logs the below, showing it has been correctly installed and configured

`LOG  NativeWind verifyInstallation() found no errors
 LOG  nativewind:  true`

I hope this helps someone.

**Comment by jrodriguezo** [comment]
use `metro.config.cjs` instead of `metro.config.js`

**Comment by emi0x7d1** [comment]
I spent hours in with this issue.

I finally got it working by deleting node_modules and deleting my lock file

**Comment by csulit** [comment]
hmmm??

› Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundling failed 555ms node_modules/.pnpm/expo-router@5.1.3_2b5f4521e88215a7c3938865a4fc843b/node_modules/expo-router/entry.js (1182 modules)
Unable to resolve "react-native-css-interop/jsx-runtime" from "app/index.tsx"

**Comment by saulflores95** [comment]
Hi everyone! If you're having the issue where nativewind styles stoped rendering after migrating from Expo 52 to 53, and are using nativewind 4 here's what resolved it for me:

Steps I followed:

Updated all dependencies - Make sure Metro, NativeWind, and related packages are on compatible versions
I Used `npx expo install --fix` (works in monorepos too - just run it from your expo app folder).


Double-checked your [NativeWind installation](https://www.nativewind.dev/docs/getting-started/installation) if you are 100% sure everything is correct. Go through [troubleshooting guide](https://www.nativewind.dev/docs/getting-started/troubleshooting). If that still does not work (which was my case).

I discovered that `react-native-css-interop` was installed in my project and conflicting with NativeWind's CSS processing. Removing this dependency completely resolved the styling issues.

`pnpm remove react-native-css-interop` (I use pnpm)
`yarn remove react-native-css-interop`
`npm uninstall react-native-css-interop`


removed all the following folders expo .cache .expo .turbo android ios node_modules and reinstalled again.

After removal of the problematic dependency and deleted cache, all styles rendered correctly again.

Hope this helps others facing the same issue!

**Comment by w4t3r-45** [comment]
am having the same issue it is telling require is not a function it is an object when i import global.css



` TypeError: require(_dependencyMap[2], "reac(...)ies/Core/Devtools/getDevServer") is not a function (it is Object), js engine: hermes`

**Comment by ansh** [comment]
The issue is that `react-native-css-interop` must have a particular version, but there may be another package that is overriding it. 

I found adding this to the `package.json` works: `"overrides": { "nativewind": { "react-native-css-interop": "0.1.22" } }`

Or simply just: `"overrides": "react-native-css-interop": "0.1.22" }` if you are using `bun` which doesn't support nested overrides.

**Comment by randypaynejr** [comment]
> The issue is that `react-native-css-interop` must have a particular version, but there may be another package that is overriding it.
> 
> I found adding this to the `package.json` works: `"overrides": { "nativewind": { "react-native-css-interop": "0.1.22" } }`
> 
> Or simply just: `"overrides": "react-native-css-interop": "0.1.22" }` if you are using `bun` which doesn't support nested overrides.

This method worked for me - thanks. Nativewind 4.2+ with css-interop 0.1.22
