### ISSUE TITLE
NativeWind not working with React Native 0.77+

### ISSUE THREAD

**Issue by minhduhung2002** [nativewind/nativewind#1579]
Describe the bug
I was using Expo SDK 52 with React Native 0.76.9 and NativeWind 4.1.23, and everything worked fine. However, after upgrading React Native to 0.77 and above, I encountered the following error right after a successful build:
ERROR  node_modules/react-native-css-interop/dist/runtime/jsx-runtime.js: 
[BABEL] /Users/xxx/Development/xxx/mobile/node_modules/react-native-css-interop/dist/runtime/jsx-runtime.js: 
Cannot find module 'react-native-worklets/plugin'

Require stack:
/Users/xxx/Development/xxx/node_modules/@babel/core/lib/config/files/plugins.js
/Users/xxx/Development/xxx/node_modules/@babel/core/lib/config/files/index.js
/Users/xxx/Development/xxx/node_modules/@babel/core/lib/index.js
/Users/xxx/Development/xxx/node_modules/metro-transform-worker/src/index.js
/Users/xxx/Development/xxx/node_modules/react-native-css-interop/dist/metro/transformer.js
/Users/xxx/Development/xxx/node_modules/metro/src/DeltaBundler/Worker.flow.js
/Users/xxx/Development/xxx/node_modules/metro/src/DeltaBundler/Worker.js
/Users/xxx/Development/xxx/node_modules/jest-worker/build/workers/processChild.js
When I removed NativeWind and rebuilt, the problem was resolved, so I assume the issue may be related to this library.
Reproduction
Steps to reproduce:
Create a new Expo SDK 52 project.
Upgrade React Native to 0.77+.
Install NativeWind 4.1.23.
Build the app.
Observe the error above.
⚠️ A minimal reproduction can be created using:
npx rn-new@latest --nativewind
npx rn-new@latest --nativewind --expo-router
Expected behavior
The app should build and run successfully without a Babel error related to react-native-worklets/plugin.
