### ISSUE TITLE
Expo v54 + EXPO ROUTER + NativeWind v5  : error global.css: failed to deserialize

### ISSUE THREAD

**Issue by Jackeish** [nativewind/nativewind#1622]

**Comment by Jackeish** [comment]
Hi guys,

my demo has same issue same with https://github.com/nativewind/nativewind/issues/1616
i do  follow https://www.nativewind.dev/v5/getting-started/installation
working with V4 is fine for me before v5

https://github.com/Jackeish/Nativewind_for_android_error.git

**Comment by danstepanov** [comment]
Closing this as a duplicate of #1613

**Comment by Jackeish** [comment]
I am using Expo v54 and Expo Router. Follow the instructions in Expo's documentation about Tailwind（ https://docs.expo.dev/guides/tailwind/ ）It can be successfully accessed on the web.
I found that according to the nativewind guidelines（ https://www.nativewind.dev/v5/getting-started/installation ）When I try to compile for Android, it always shows a compilation error for the specified global CSS file. Later on, I discovered that converting CSS to a stylesheet using React Native CSS required the use of the LightningCSS package, but both Expo and React Native CSS were not actively dependent during installation. Finally, I found that the error occurred in react native css \ dist \ commonjs \ compiler \ compiler. js LINE 102: lightningcss, where the execution went wrong.
When I installed the lightningcss package, I found that on the window platform, it would direct to the lightningcss-win32-x64-msvc package, only to the. node file. I found that 'logger (Lightningcss second pass);' cannot be executed when debugging compiler. js.

**Comment by Jackeish** [comment]
LightningCSS ":" 1.30.1 "
Do not use versions above 1.30.1 with React native CSS
react-native-css："^3.0.0" works with  LightningCSS ":" 1.30.1 "
